export const SocketContextDefaultState = {
    players: [],
    gameId: '',
    playerName: '',
    playerId: '',
    notifyPlayersMessage: '',
    side: 'ROLL',
    card: 'DRAW',
    cardsLeft: 0,
    isDiceRolled: false,
    isCardDrawn: false,
    createGameMessage: '',
    joinedGameMessage: '',
    changePlayerMessage: '',
    loser: null,
    gameStartedMessage: '',
    playerDisconnectMessage: '',
    bombPassedMessage: '',
    updateGameDataErrorMessage: '',
    roundStarted: false,
    roundEnded: false,
    gameOver: false,
    playTickAudio: false,
    playBoomAudio: false,
    gameMasterChangedMessage: '',
    playerDisconnectedMessage: '',
}